FROM python:3.12-slim

WORKDIR /app

COPY requirements/producer.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY config /app/config
COPY src /app/src

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "src.producer.main"]
